[[headers]]
  for = "/*.js"
  [headers.values]
  Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
  Content-Type = "text/javascript; charset=utf-8"

[[redirects]]
  from = "/scripts/*"
  to = "/scripts/:splat"
  status = 200

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200

[[redirects]]
  from = "/styles/*"
  to = "/styles/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200