export const NHS_LINKS={
  "HbA1c":"https://www.nhs.uk/conditions/type-2-diabetes/diagnosis/",
  "Fasting Glucose":"https://www.nhs.uk/conditions/type-2-diabetes/diagnosis/",
  "Random Glucose":"https://www.nhs.uk/conditions/type-2-diabetes/diagnosis/",
  "Oral Glucose Tolerance 2h":"https://www.nhs.uk/conditions/type-2-diabetes/diagnosis/",
  "Total Cholesterol":"https://www.nhs.uk/conditions/high-cholesterol/",
  "LDL Cholesterol":"https://www.nhs.uk/conditions/high-cholesterol/",
  "HDL Cholesterol":"https://www.nhs.uk/conditions/high-cholesterol/",
  "Triglycerides":"https://www.nhs.uk/conditions/high-cholesterol/",
  "Non-HDL Cholesterol":"https://www.nhs.uk/conditions/high-cholesterol/",
  "Apolipoprotein B":"https://www.nhs.uk/conditions/high-cholesterol/",
  "Lipoprotein(a)":"https://www.nhs.uk/conditions/high-cholesterol/",
  "Urea":"https://www.nhs.uk/conditions/kidney-disease/",
  "Creatinine":"https://www.nhs.uk/conditions/kidney-disease/",
  "eGFR":"https://www.nhs.uk/conditions/kidney-disease/",
  "Cystatin C":"https://www.nhs.uk/conditions/kidney-disease/",
  "Urine ACR":"https://www.nhs.uk/conditions/kidney-disease/",
  "Urine PCR":"https://www.nhs.uk/conditions/kidney-disease/",
  "Sodium":"https://www.nhs.uk/conditions/hyponatraemia/",
  "Potassium":"https://www.nhs.uk/conditions/hyperkalaemia/",
  "Calcium":"https://www.nhs.uk/conditions/hypercalcaemia/",
  "Phosphate":"https://www.nhs.uk/conditions/kidney-disease/",
  "Magnesium":"https://www.nhs.uk/conditions/magnesium-deficiency/",
  "ALT":"https://www.nhs.uk/conditions/liver-disease/",
  "AST":"https://www.nhs.uk/conditions/liver-disease/",
  "ALP":"https://www.nhs.uk/conditions/liver-disease/",
  "GGT":"https://www.nhs.uk/conditions/liver-disease/",
  "Bilirubin":"https://www.nhs.uk/conditions/jaundice/",
  "Albumin":"https://www.nhs.uk/conditions/liver-disease/",
  "Total Protein":"https://www.nhs.uk/conditions/liver-disease/",
  "Globulin":"https://www.nhs.uk/conditions/liver-disease/",
  "CRP":"https://www.nhs.uk/conditions/fever-in-adults/",
  "ESR":"https://www.nhs.uk/conditions/arthritis/",
  "TSH":"https://www.nhs.uk/conditions/underactive-thyroid-hypothyroidism/",
  "Free T4":"https://www.nhs.uk/conditions/underactive-thyroid-hypothyroidism/",
  "Free T3":"https://www.nhs.uk/conditions/overactive-thyroid-hyperthyroidism/",
  "Thyroid Peroxidase Antibodies":"https://www.nhs.uk/conditions/thyroiditis/",
  "25-OH Vitamin D":"https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-d/",
  "Vitamin B12":"https://www.nhs.uk/conditions/vitamin-b12-or-folate-deficiency-anaemia/",
  "Folate":"https://www.nhs.uk/conditions/vitamin-b12-or-folate-deficiency-anaemia/",
  "Ferritin":"https://www.nhs.uk/conditions/iron-deficiency-anaemia/",
  "Serum Iron":"https://www.nhs.uk/conditions/iron-deficiency-anaemia/",
  "TIBC":"https://www.nhs.uk/conditions/iron-deficiency-anaemia/",
  "Transferrin":"https://www.nhs.uk/conditions/iron-deficiency-anaemia/",
  "Transferrin Saturation":"https://www.nhs.uk/conditions/iron-deficiency-anaemia/",
  "Uric Acid":"https://www.nhs.uk/conditions/gout/",
  "Amylase":"https://www.nhs.uk/conditions/acute-pancreatitis/",
  "Lipase":"https://www.nhs.uk/conditions/acute-pancreatitis/",
  "Troponin (hs)":"https://www.nhs.uk/conditions/heart-attack/",
  "NT-proBNP":"https://www.nhs.uk/conditions/heart-failure/",
  "INR":"https://www.nhs.uk/conditions/anticoagulants/",
  "Prothrombin Time (PT)":"https://www.nhs.uk/conditions/anticoagulants/",
  "aPTT":"https://www.nhs.uk/conditions/anticoagulants/",
  "D-dimer":"https://www.nhs.uk/conditions/deep-vein-thrombosis-dvt/",
  "Fibrinogen":"https://www.nhs.uk/conditions/",
  "WBC":"https://www.nhs.uk/conditions/infections/",
  "Neutrophils":"https://www.nhs.uk/conditions/infections/",
  "Lymphocytes":"https://www.nhs.uk/conditions/infections/",
  "Monocytes":"https://www.nhs.uk/conditions/infections/",
  "Eosinophils":"https://www.nhs.uk/conditions/allergies/",
  "Basophils":"https://www.nhs.uk/conditions/",
  "RBC":"https://www.nhs.uk/conditions/anaemia/",
  "Haemoglobin":"https://www.nhs.uk/conditions/anaemia/",
  "Haematocrit":"https://www.nhs.uk/conditions/anaemia/",
  "Mean Cell Volume":"https://www.nhs.uk/conditions/anaemia/",
  "MCH":"https://www.nhs.uk/conditions/anaemia/",
  "MCHC":"https://www.nhs.uk/conditions/anaemia/",
  "RDW":"https://www.nhs.uk/conditions/anaemia/",
  "Reticulocytes":"https://www.nhs.uk/conditions/anaemia/",
  "Platelets":"https://www.nhs.uk/conditions/thrombocytopenia/",
  "PTH":"https://www.nhs.uk/conditions/hyperparathyroidism/",
  "Blood Pressure":"https://www.nhs.uk/common-health-questions/lifestyle/what-is-blood-pressure/"
};